# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIPosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('full', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='apidata',
            name='expandedLinks',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='postUrl',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='media',
            name='api_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIPosts.APIData'),
        ),
    ]
