# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPosts', '0002_auto_20160731_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='api_id',
            field=models.IntegerField(unique=True),
        ),
    ]
