# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIPosts', '0005_auto_20160731_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualstatistics',
            name='api_data',
        ),
        migrations.AddField(
            model_name='apidata',
            name='act_statistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIPosts.ActualStatistics'),
        ),
    ]
