# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIPosts', '0006_auto_20160731_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='api_data',
        ),
        migrations.AddField(
            model_name='apidata',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIPosts.Account'),
        ),
    ]
