# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIPosts', '0007_auto_20160731_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profileImage',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='expandedLinks',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='postUrl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='full',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
